version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: cloudflow-saas
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped
    networks:
      - cloudflow-network

  # Optional: Add a development server
  dev:
    image: node:18-alpine
    container_name: cloudflow-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - cloudflow-network

networks:
  cloudflow-network:
    driver: bridge 